algoritmo "soma"
// F9: Executa o código

// Autor: Thiago Marcelino Vieira
// Disciplina: LOPAL
// Data: 13/04/2026
var
   n1, n2, n3, soma: real
inicio
   // Entrada
   escreva ("Informe o primeiro número: ")
   leia (n1)
   
   escreva ("Informe o segundo número: ")
   leia (n2)

   escreva ("Informe o terceiro número: ")
   leia (n3)
   
   // Processo
   soma <- n1 + n2 + n3
   
   // Saída
   limpatela
   
   escreva ("A soma de", n1, ",", n2, " e", n3, " é:", soma, ".")
fimalgoritmo
