algoritmo "dirigir"
// F9: Executa o código

// Autor: Thiago Marcelino Vieira
// Disciplina: LOPAL
// Data: 13/04/2026
var
   idade: inteiro
inicio
   // Entrada
   escreva ("Informe uma idade: ")
   leia (idade)
   
   // Processo
   se idade >= 18 entao
   // Saída
      limpatela
      escreva ("Pode dirigir!")
   senao
      limpatela
      escreva ("Ainda não pode dirigir...")
   fimse
   
fimalgoritmo
