algoritmo "senha"
// F9: Executa o código

// Autor: Thiago Marcelino Vieira
// Disciplina: LOPAL
// Data: 13/04/2026
var
   nome, senha: caracter
inicio
   // Entrada
   escreva ("Nome de usuário: ")
   leia (nome)
   
   escreva ("Senha: ")
   leia (senha)
   
   // Processo
   se senha = "acb23" entao
   // Saída
      limpatela
      escreva ("Login efetuado com sucesso!")
   senao
      limpatela
      escreva ("Senha incorreta, tente novamente.")
   fimse
   
fimalgoritmo
